### ISSUE TITLE
Bug Report: APIStuff.hx is not included

### ISSUE THREAD

**Issue by Leather128** [Rageminer996/Smoke-Em-Out-Struggle-Mod#4]
Ok so basically when you try to compile the game it gives this error message:

![image](https://user-images.githubusercontent.com/81660872/118897821-11254000-b8d9-11eb-86bd-db5528c47b19.png)

If you're wondering, yes I know you can just add this yourself easily but I feel like it should be included in the main repository.
To do this, you would just have to get rid of APIStuff.hx from .gitignore.
And then push the update out.

**Comment by DotWith** [comment]
WTF. Ok, First don't remove it from ".gitignore" thats a very bad idea pls guys don't do this. The reason for "APIStuff.hx" to be excluded from push updates this is to insure that no one takes your Newgrounds API and such. You don't want them to be like i'm going to mess this this API Key and unlock every achievement. >:(

**Comment by Leather128** [comment]
Thanks for informing me because I actually didn't know what it was for. If I did I might've been a bit more considerate.
