### ISSUE TITLE
Bug Report: Type not found while compiling

### ISSUE THREAD

**Issue by Maritsu** [Rageminer996/Smoke-Em-Out-Struggle-Mod#6]
### If you are playing a downloaded version of the game, what operating system are you using?

Compiling source code, Ubuntu 20.04.2 LTS 64-bit, Linux 5.8.0-53-generic

## What version of the game are you using? Look in the bottom left corner of the main menu.
The latest version of the source code.

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Download all the required `haxe` libraries, clone the source code and run `$ lime test linux -debug`
![Terminal screenshot](https://user-images.githubusercontent.com/66056347/119255474-55a42a80-bbbc-11eb-8d65-2d560c4f3c95.png)

## Please describe your issue. Provide extensive detail and images if possible.
As the image above shows, upon running `$ lime test linux -debug`, an error message is shown:
```
source/TitleState.hx:61: characters 16-28 : Type not found : APIStuff
/home/bittheprotogen/haxelib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
/home/bittheprotogen/haxelib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
```

**Comment by DotWith** [comment]
#4 Willl help you and please after reading close this issue and pull request.

**Comment by Maritsu** [comment]
Oh ok, thank you
