### ISSUE TITLE
Question: Linux Builds

### ISSUE THREAD

**Issue by LividJava** [Rageminer996/Smoke-Em-Out-Struggle-Mod#9]
I'm currently compiling the mod from source using information from the [main branch](https://github.com/ninjamuffin99/Funkin#build-instructions).
As of now there isn't any linux builds on gamebanana, are there plans for making some or is it solely windows?

**Comment by ghost** [comment]
I can send you a Linux build zip if you want.
Are you on Ubuntu 21.04/have glibc 2.33?

**Comment by ghost** [comment]
Will send a link to a probably universally compatible version in 5 minutes

**Comment by LividJava** [comment]
I've compiled the binaries myself already... just didnt know if there was any plans for having linux builds as most mods i've seen either dont support linux or forget it exists entirely

**Comment by ghost** [comment]
ah

**Comment by LividJava** [comment]
I did go ahead and repost the mod on [gamebanana](https://gamebanana.com/mods/289991) working under the license agreement on this repo. It does have dfkj and wasd control variants though lol
